title: Scrcpy GUI
window:
  size:
    width: 600
    height: 128
  position:
    x: 200
    y: 400

contents:
  - x: 448
    y: 100
    type: link
    path: '/Applications'
  - x: 192
    y: 100
    type: file
    path: Scrcpy GUI.app
