// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> getAppIcon(
        {required String apkPath, required bool deleteApkAfterProcessing}) =>
    RustLib.instance.api.crateApiApkexGetAppIcon(
        apkPath: apkPath, deleteApkAfterProcessing: deleteApkAfterProcessing);

Future<String> pullApk(
        {required String adbPath,
        required String deviceId,
        required String packageName,
        required String outputDirPath}) =>
    RustLib.instance.api.crateApiApkexPullApk(
        adbPath: adbPath,
        deviceId: deviceId,
        packageName: packageName,
        outputDirPath: outputDirPath);
